name: ğŸš€ Build & Publish Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸšš Check out the Repo
        uses: actions/checkout@v3
    
      - name: ğŸ“ Build and push Docker image
        run: |
            echo "${{ secrets.docker_password }}" | docker login --username ${{ secrets.docker_username }} --password-stdin
            docker build -t redwanh25/cicdproject:v1 .
            docker push redwanh25/cicdproject:v1
